### ISSUE TITLE
What should $Display be set too when running on a headless server

### ISSUE THREAD

**Issue by boywiz** [baptistecdr/docker-lsi-megaraid-storage-manager#11]
when i run the following:

`
docker run --rm --privileged \
--mount type=bind,source="$HOME/.Xauthority",target=/root/.Xauthority \
--mount type=bind,source=/tmp/.X11-unix,target=/tmp/.X11-unix \
-e TZ="Europe/Paris" \
-e ROOT_PASSWORD="myrootpassword" \
-e DISPLAY=$DISPLAY \
--network host baptistecdr/lsi-megaraid-storage-manager
`
i get the following error what should this be set to?

`
X11 Display variable is not properly set
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at sun.awt.HeadlessToolkit.getScreenSize(HeadlessToolkit.java:284)
        at GUI.VivaldiStartupDialog.main(Unknown Source)
`

I have tried setting the $DISPLAY to:
localhost:0.0
:0
0:0

x11 is not installed or active on my server 

I am running on:
Ubuntu 20.04.4 LTS SERVER
20.04.4 LTS (Focal Fossa)
Ubuntu 20.04.4 LTS
x86
Docker 20.10.17
docker-compose 1.27.4

**Comment by baptistecdr** [comment]
Hi @boywiz ,

Thank you for the issue.

I don't have a lot of experience with x11, but I guess you need some x11 packages installed on your headless server.

Did you try the first part of this article: https://www.elliotsegler.com/headless-x11-forwarding.html ?

Have a nice day,
baptistecdr

**Comment by boywiz** [comment]
> Hi @boywiz ,
> 
> Thank you for the issue.
> 
> I don't have a lot of experience with x11, but I guess you need some x11 packages installed on your headless server.
> 
> Did you try the first part of this article: https://www.elliotsegler.com/headless-x11-forwarding.html ?
> 
> Have a nice day, baptistecdr

Thanks for the Rapid reply, I have tried that again just to make sure, but i do not get a Display value. i will investigate, i was hoping you had a quick answer

**Comment by baptistecdr** [comment]
You're welcome.

If you find the solution, don't forget to share it here so we can learn how to do that. :)
