### ISSUE TITLE
Can't connect to Xserver + correction to Xauthority loc

### ISSUE THREAD

**Issue by ato2** [baptistecdr/docker-lsi-megaraid-storage-manager#111]
Ubuntu 23.10 + podman 
Anu clue ?

% cat docker-compose.yml 
version: "3.9"
services:
  lsi-megaraid-storage-manager:
    container_name: lsi-megaraid-storage-manager
    image: baptistecdr/lsi-megaraid-storage-manager:4.1.3@sha256:573763a38105dc0116e8668ca143bbef1f26de5f92fe647f86d912385c60debe
    privileged: true
    environment:
      - TZ=Europe/Warsaw
      - ROOT_PASSWORD=pass1
      - DISPLAY=:1
    volumes:
      - /run/user/1000/gdm/Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host

% echo $DISPLAY
:1

% ls -l /run/user/1000/gdm/Xauthority
-rwx------ 1 stud stud 92 Nov  6 19:31 /run/user/1000/gdm/Xauthority

% pgrep -lfa Xorg
71879 /usr/lib/xorg/Xorg vt2 -displayfd 3 -auth /run/user/1000/gdm/Xauthority -nolisten tcp -background none -noreset -keeptty -novtswitch -verbose 3

% sudo docker-compose up
Starting lsi-megaraid-storage-manager ... done
Attaching to lsi-megaraid-storage-manager
lsi-megaraid-storage-manager    | Changing password for user root.
lsi-megaraid-storage-manager    | passwd: all authentication tokens updated successfully.
lsi-megaraid-storage-manager    | Starting Framework:
lsi-megaraid-storage-manager    | Authorization required, but no authorization protocol specified
lsi-megaraid-storage-manager    | Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':1' as the value of the DISPLAY variable.
lsi-megaraid-storage-manager    |       at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
lsi-megaraid-storage-manager    |       at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
lsi-megaraid-storage-manager    |       at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
lsi-megaraid-storage-manager    |       at java.security.AccessController.doPrivileged(Native Method)
lsi-megaraid-storage-manager    |       at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
lsi-megaraid-storage-manager    |       at java.lang.Class.forName0(Native Method)
lsi-megaraid-storage-manager    |       at java.lang.Class.forName(Class.java:264)
lsi-megaraid-storage-manager    |       at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
lsi-megaraid-storage-manager    |       at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
lsi-megaraid-storage-manager    |       at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:131)
lsi-megaraid-storage-manager    |       at java.lang.Class.forName0(Native Method)
lsi-megaraid-storage-manager    |       at java.lang.Class.forName(Class.java:264)
lsi-megaraid-storage-manager    |       at java.awt.Toolkit$2.run(Toolkit.java:860)
lsi-megaraid-storage-manager    |       at java.awt.Toolkit$2.run(Toolkit.java:855)
lsi-megaraid-storage-manager    |       at java.security.AccessController.doPrivileged(Native Method)
lsi-megaraid-storage-manager    |       at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
lsi-megaraid-storage-manager    |       at sun.swing.SwingUtilities2.getSystemMnemonicKeyMask(SwingUtilities2.java:2032)
lsi-megaraid-storage-manager    |       at javax.swing.plaf.basic.BasicLookAndFeel.initComponentDefaults(BasicLookAndFeel.java:1158)
lsi-megaraid-storage-manager    |       at javax.swing.plaf.metal.MetalLookAndFeel.initComponentDefaults(MetalLookAndFeel.java:431)
lsi-megaraid-storage-manager    |       at javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:148)
lsi-megaraid-storage-manager    |       at javax.swing.plaf.metal.MetalLookAndFeel.getDefaults(MetalLookAndFeel.java:1577)
lsi-megaraid-storage-manager    |       at javax.swing.UIManager.setLookAndFeel(UIManager.java:539)
lsi-megaraid-storage-manager    |       at javax.swing.UIManager.setLookAndFeel(UIManager.java:579)
lsi-megaraid-storage-manager    |       at javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1349)
lsi-megaraid-storage-manager    |       at javax.swing.UIManager.initialize(UIManager.java:1459)
lsi-megaraid-storage-manager    |       at javax.swing.UIManager.maybeInitialize(UIManager.java:1426)
lsi-megaraid-storage-manager    |       at javax.swing.UIManager.getDefaults(UIManager.java:659)
lsi-megaraid-storage-manager    |       at GUI.VivaldiStartupDialog.<clinit>(Unknown Source)
lsi-megaraid-storage-manager exited with code 1

**Comment by ato2** [comment]
solved

**Comment by baptistecdr** [comment]
Alright, what was the problem?
